[2024-05-14T06:48:04.004+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-14T06:48:04.033+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: json_to_csv_database_b.boygroup_transform scheduled__2024-05-14T06:46:00+00:00 [queued]>
[2024-05-14T06:48:04.038+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: json_to_csv_database_b.boygroup_transform scheduled__2024-05-14T06:46:00+00:00 [queued]>
[2024-05-14T06:48:04.039+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-05-14T06:48:04.045+0000] {taskinstance.py:2330} INFO - Executing <Task(_PythonDecoratedOperator): boygroup_transform> on 2024-05-14 06:46:00+00:00
[2024-05-14T06:48:04.051+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3421) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-05-14T06:48:04.053+0000] {standard_task_runner.py:63} INFO - Started process 3433 to run task
[2024-05-14T06:48:04.054+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'json_to_csv_database_b', 'boygroup_transform', 'scheduled__2024-05-14T06:46:00+00:00', '--job-id', '389', '--raw', '--subdir', 'DAGS_FOLDER/json_to_csv_database_b.py', '--cfg-path', '/tmp/tmp408474oe']
[2024-05-14T06:48:04.056+0000] {standard_task_runner.py:91} INFO - Job 389: Subtask boygroup_transform
[2024-05-14T06:48:04.085+0000] {task_command.py:426} INFO - Running <TaskInstance: json_to_csv_database_b.boygroup_transform scheduled__2024-05-14T06:46:00+00:00 [running]> on host 7331c320d95e
[2024-05-14T06:48:04.187+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='json_to_csv_database_b' AIRFLOW_CTX_TASK_ID='boygroup_transform' AIRFLOW_CTX_EXECUTION_DATE='2024-05-14T06:46:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-05-14T06:46:00+00:00'
[2024-05-14T06:48:04.189+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-14T06:48:04.190+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-14T06:48:04.190+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/decorators/base.py", line 265, in execute
    return_value = super().execute(context)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/json_to_csv_database_b.py", line 48, in transform
    o += ",".join([str(a[column]) for column in columns]) + "\n"
                       ~^^^^^^^^
KeyError: 'debut_date'
[2024-05-14T06:48:04.197+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=json_to_csv_database_b, task_id=boygroup_transform, run_id=scheduled__2024-05-14T06:46:00+00:00, execution_date=20240514T064600, start_date=20240514T064804, end_date=20240514T064804
[2024-05-14T06:48:04.202+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 389 for task boygroup_transform ('debut_date'; 3433)
[2024-05-14T06:48:04.237+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-05-14T06:48:04.250+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-05-14T06:48:04.252+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
